"""/v1/co 单据通用路由（co_table）的操作说明。"""

from u8co_api.co_models_arap import ARAP_ROUTE_HELP

LOAD_HELP = (
    "按类型和主键读取单据的表头、明细和审核状态。\n\n"
    "**用法**\n"
    "- 含调拨单、销售发票、采购发票、生产订单、收款单、付款单、应收单和应付单。\n"
    "- 检验单和不良品处理单另附审批状态。\n"
    "- 来料报检单、产品报检单另附来源单据 source（到货单或生产订单）。\n"
    "- 物料清单（bom）：id 是 BomId，code 是母件存货编码。\n"
    "- 物料清单的 head / lines 的键是小写下划线。\n\n"
    "**限制**\n"
    "- 物料清单只读标准 BOM。"
)

VERIFY_HELP = (
    "按单据类型审核或弃审单据。\n\n"
    "**用法**\n"
    "- 采购发票的 verify 是采购复核（取消复核），销售发票的 verify 是销售复核。\n"
    "- 调拨单审核可以返回生成的其他出入库单。\n"
    "- 收款单、付款单、应收单和应付单走应收应付模块的审核。\n"
    "- 生产订单审核即 U8 的审核（下达），id 是 MoId；全部明细审核后 state.verified 为 true。\n"
    "- 请购单审核、弃审走采购的 ConfirmApp / CancelconfirmApp。\n"
    "- 物料清单（bom，id 是 BomId）走 U8API BomAuditing / BomUnauditing。\n"
    + ARAP_ROUTE_HELP
    + "\n**限制**\n"
    "- 检验单和不良品处理单不能直接审核，请用 workflow/*。\n"
    "- 来料报检单不支持单独审核、弃审：U8 保存时按选项自动审核，删除时桥会先弃审。\n"
    "- 产品报检单只支持弃审（action=unverify）。\n"
    "- 已被采购订单参照的请购单不能弃审。\n\n"
    "**错误**\n"
    "- 物料清单版本受审批流控制：409 workflow_enabled。"
)

CREATE_HELP = (
    "新增单据。\n\n"
    "**用法**\n"
    "- 常用类型：销售订单、采购订单、其他入库单、其他出库单、调拨单、收款单、付款单、应收单和应付单。\n"
    "- 全部类型见 type。\n"
    "- 表头和明细的值不能嵌套。\n"
    "- 收款单、付款单、应收单、应付单：表头用 U8 列名，必须有 cDwCode；每行 iAmt 必须大于 0。\n"
    "- 收款单、付款单：表头还要 cSSCode 和 cCode。\n"
    "- 供应商退款（ap_refund，AP48，往来单位是供应商）、客户退款（ar_refund，AR49，往来单位是客户）同收付款单。\n"
    "- 退款金额填正数，审核时 U8 在往来明细里记负数。\n"
    "- 请购单（purchase_requisition）：明细必须有 cinvcode 和大于 0 的 fquantity；单价只收 ioricost 或 ioritaxcost。\n"
    "- 形态转换单（shape_change）：每行要有 cwhcode、bavtype（转换前 / 转换后）和大于 0 的 iavquantity。\n"
    "- 形态转换单按 igroupno 成组。\n"
    "- 调拨申请单（transfer_request）：表头要有 cowhcode、ciwhcode。\n"
    "- 盘点单（stock_check）：表头要有 cwhcode；每行要有 icvcquantity（实盘，可为 0）。\n"
    "- 盘点单的账面数量 icvquantity 不给时按现存量填。\n"
    "- 生产订单（production_order）走 U8API MOrderAdd，字段见 lines 的说明。\n"
    "- 生产订单由 U8 自动编号并按标准 BOM 展开子件；响应另有 allocates、details 和 warnings。\n"
    "- 物料清单（bom）走 U8API BomAdd，建母件的一个标准 BOM 新版本；响应另有 version 和 components。\n"
    "- 采购结算单（purchase_settle）是手工结算，按 U8 手工结算界面执行的 SQL 写（实测核对）。\n"
    "- 采购结算单明细 1 到 400 行：入库行、发票行配对，或红蓝入库对冲、红蓝发票对冲。\n"
    "- 采购结算单响应另有 settle_date；删除走 vouchers/delete。\n"
    "- 期初结存单（stock_opening，U8 单据类型 34）：\n"
    "  - 走 U8 官方 EAI 导入（storeqc），每行建成一张单据。\n"
    "  - 响应 docs 逐张列出 id、code、line、wh、inv、qty；顶层 id、code 是第一张，另有 count、date。\n"
    "  - 字段名单见 docs/api-reference.md；行上的 cwhcode 覆盖表头。\n"
    "  - 日期固定为库存启用日前一天（传入的不用，见 warnings）。\n"
    "  - 预演只做调用前的检查（validate），不导入。\n\n"
    "**限制**\n"
    "- 期初结存单默认关闭：桥未开 enableReplicatedWrites 时 403 feature_disabled。\n"
    "- 期初结存单打开后只对 CO 桥配置为测试账套的账套开放，其他账套 403 test_account_only。\n"
    "- 期初结存单不能修改，请删除后重新录入。\n"
    "- 采购结算单不只限测试账套，按写入策略放行。\n\n"
    "**错误**\n"
    "- 期初结存单：存货核算已期初记账 409 state_mismatch；库存启用月已月结时 U8 拒绝 409 u8_rejected。\n"
    "- 生产订单：U8 拒绝 409 u8_rejected；生产制造服务未运行 503 u8_unavailable。\n"
    "- 生产订单：调用异常且回读不到新订单 504 outcome_unknown（不要重投，先按单号或列表核对）。\n"
    "- 物料清单：版本号或生效日期与已有版本重复 409 state_mismatch；其余结果码同生产订单。"
)

DELETE_HELP = (
    "删除未审核的单据。\n\n"
    "**用法**\n"
    "- 包括销售订单、其他入库单、其他出库单、采购订单、调拨单、发货单、到货单、销售出库单。\n"
    "- 包括采购入库单、销售发票、采购发票、收款单、付款单、应收单和应付单。\n"
    "- 生产订单（id 是 MoId）走 U8API MOrderDelete。\n"
    "- 物料清单（id 是 BomId）走 U8API BomDelete。\n\n"
    "**限制**\n"
    "- 材料出库单、产成品入库单：只删除参照生产订单或产品检验单生成的未审核单据。\n"
    "- 已生成凭证或已核销的收付款单和应收应付单不能删除。\n"
    "- 请购单：只删除未审核、未关闭、未被采购订单参照的单据。\n"
    "- 生产订单：只删除全部行未审核、未提交审批、未被材料出库或产成品入库引用的订单。\n"
    "- 物料清单：只删除未审核、未进审批流且没有被引用的版本。\n"
    "- 物料清单的引用方：生产订单、委外订单、组装 / 拆卸 / 形态转换单、配比出库单、调拨单。\n"
    "- 来料报检单、产品报检单：只删除没有检验单引用的单据；已审核的先弃审再删除。\n"
    "- 来料检验单、产品检验单：只删除未审核、未提交审批的单据。\n"
    "- 检验单被采购入库 / 产成品入库或不良品处理单引用时不能删除。\n\n"
    "**错误**\n"
    "- 删除已审核的报检单要有弃审权限，否则 409。\n"
    "- 报检单、检验单的删除由 U8 自己提交：调用异常且回读不清时 504 outcome_unknown。"
)

UPDATE_HELP = (
    "修改未审核、未关闭且没有下游的单据。\n\n"
    "**用法**\n"
    "- head 与 lines 至少给一个非空。\n"
    "- lines 的 op 为 add、update 或 delete。\n"
    "- 生产订单（id 是 MoId）走 U8API MOrderLoad + MOrderUpdate，行按 line_id 定位。\n"
    "- 生产订单：桥把加载出的子件全部重送，改了数量的行按 U8 的算法重算子件数量。\n"
    "- 生产订单：桥写回 U8 重插时丢掉的关联列；响应另有 allocates、details、changed。\n"
    "- 物料清单（bom）：明细按 sort_seq 定位，桥读出全部行、叠上修改后整套送 U8API BomUpdate。\n\n"
    "**限制**\n"
    "- 生产订单只改未审核、无下游的订单；不能增删行、换存货。\n"
    "- 物料清单只改未审核的标准 BOM。\n\n"
    "**错误**\n"
    "- 生产订单修改后回读子件对不上：504 outcome_unknown（不要重投，先读取核对）。\n"
    "- 物料清单行上有替代料、定位符等接口带不回去的内容：409 state_mismatch。"
)

CLOSE_HELP = (
    "关闭或打开单据，整单或按行。\n\n"
    "**用法**\n"
    "- 类型见 type：销售订单、采购订单、请购单、生产订单和到货单。\n"
    "- action 为 close 或 open。\n"
    "- line_ids 省略时处理整张单据。\n"
    "- 生产订单的 id 是 MoId、line_ids 是 MoDId。\n"
    "- 生产订单省略 line_ids 时处理全部状态相符的行：关闭取已审核行，打开取已关闭行。\n\n"
    "**限制**\n"
    "- 请购单只能整单关闭或打开，不能带 line_ids。\n"
    "- 生产订单：本月已做成本计算、还有在制品、审批流控制的行都拒绝。"
)

GENERATE_HELP = (
    "按来源单据参照生成下游单据，新单据保持未审核。\n\n"
    "**用法**\n\n"
    "| 目标单据 | 来源单据 | 要求 |\n"
    "|---|---|---|\n"
    "| 发货单 | 销售订单 | — |\n"
    "| 销售出库 | 发货单 | 不能带表头；不带 lines 整张生成，带 lines 按行部分生成 |\n"
    "| 采购入库 | 采购订单 | — |\n"
    "| 采购入库 | 来料检验单（source_type=qm_incoming_check） | 只能 1 行，表头必须有 cWhCode |\n"
    "| 红字采购入库 | 采购退货单（source_type=purchase_return） | 表头必须有 cWhCode |\n"
    "| 销售发票 | 发货单 | — |\n"
    "| 采购发票 | 采购入库单 | 表头 cPBVCode 必填；红字入库单生成红字发票 |\n"
    "| 到货单 | 采购订单（id 是 POID） | 表头只收 cWhCode、dDate、cMemo、cDepCode |\n"
    "| 材料出库 | 生产订单 | 表头必须有 cWhCode |\n"
    "| 产成品入库 | 产品检验单 | 只能 1 行，表头必须有 cWhCode |\n"
    "| 来料报检单 | 已审核的蓝字到货单 | U8 保存时按设置自动审核，响应 state 为回读结果 |\n"
    "| 产品报检单 | 已审核的生产订单 | 同来料报检单 |\n"
    "| 来料检验单、产品检验单 | 已审核的报检单 | 只能 1 行，表头必须有 cCheckPersonCode |\n"
    "| 调拨单 | 已审核的调拨申请单（source_type=transfer_request） | 仓库取自申请单 |\n\n"
    "**规则**\n"
    "- 检验单的检验方案 project_code 省略时取该存货最近一张检验单的方案，都没有时 400。\n"
    "- 新检验单未提交审批，响应另有 wf。\n"
    "- 调拨单数量不超过核准数量减累计调拨数量；U8 回写申请单行累计调拨数量。\n\n"
    "**错误**\n"
    "- U8 单据模板设为必输而请求没给、桥也推不出的字段：400 bad_request，一次列出全部。\n"
    "- 检验单的新增由 U8 自己提交：调用异常且回读不到新单 504 outcome_unknown。"
)
